const empData = [
  {
    id: 1,
    name: "Amit",
    role: "Full Stack Developer",
    bio: "Passionate about building scalable web apps.",
    gender: "Male",
  },
  {
    id: 2,
    name: "Aarav",
    role: "Data Scientist",
    bio: "Loves extracting insights from big data.",
    gender: "Male",
  },
  {
    id: 3,
    name: "Ananya",
    role: "UI/UX Designer",
    bio: "Designs intuitive and user-friendly interfaces.",
    gender: "Female",
  },
  {
    id: 4,
    name: "Vihaan",
    role: "Cybersecurity Analyst",
    bio: "Keeps systems secure from vulnerabilities.",
    gender: "Male",
  },
  {
    id: 5,
    name: "Ishika",
    role: "Machine Learning Engineer",
    bio: "Works on AI models to solve real-world problems.",
    gender: "Female",
  },
  {
    id: 6,
    name: "Krishna",
    role: "DevOps Engineer",
    bio: "Automates workflows to streamline deployments.",
    gender: "Male",
  },
  {
    id: 7,
    name: "Neha",
    role: "Frontend Developer",
    bio: "Focuses on creating responsive web designs.",
    gender: "Female",
  },
  {
    id: 8,
    name: "Rohit",
    role: "Backend Developer",
    bio: "Specializes in server-side logic and APIs.",
    gender: "Male",
  },
  {
    id: 9,
    name: "Aisha",
    role: "Product Manager",
    bio: "Bridges the gap between tech and business needs.",
    gender: "Female",
  },
  {
    id: 10,
    name: "Aryan",
    role: "Mobile App Developer",
    bio: "Builds native apps for iOS and Android.",
    gender: "Male",
  },
  {
    id: 11,
    name: "Sanya",
    role: "Software Tester",
    bio: "Ensures quality by finding and fixing bugs.",
    gender: "Female",
  },
  {
    id: 12,
    name: "Kartik",
    role: "Cloud Engineer",
    bio: "Works on cloud solutions and infrastructure.",
    gender: "Male",
  },
  {
    id: 13,
    name: "Riya",
    role: "Database Administrator",
    bio: "Manages and optimizes databases.",
    gender: "Female",
  },
  {
    id: 14,
    name: "Aditya",
    role: "AI Specialist",
    bio: "Explores cutting-edge AI technologies.",
    gender: "Male",
  },
  {
    id: 15,
    name: "Meera",
    role: "Scrum Master",
    bio: "Facilitates Agile processes within teams.",
    gender: "Female",
  },
  {
    id: 16,
    name: "Arjun",
    role: "Blockchain Developer",
    bio: "Passionate about decentralized systems.",
    gender: "Male",
  },
  {
    id: 17,
    name: "Naina",
    role: "Technical Writer",
    bio: "Creates documentation for technical projects.",
    gender: "Female",
  },
  {
    id: 18,
    name: "Ravi",
    role: "Game Developer",
    bio: "Brings virtual worlds to life.",
    gender: "Male",
  },
  {
    id: 19,
    name: "Sara",
    role: "IoT Developer",
    bio: "Works on smart device integrations.",
    gender: "Female",
  },
  {
    id: 20,
    name: "Kabir",
    role: "IT Support Specialist",
    bio: "Solves IT issues to keep systems running.",
    gender: "Male",
  },
  {
    id: 21,
    name: "Tara",
    role: "AI Researcher",
    bio: "Explores new frontiers in artificial intelligence.",
    gender: "Female",
  },
  {
    id: 22,
    name: "Vikram",
    role: "Network Engineer",
    bio: "Ensures smooth and secure network operations.",
    gender: "Male",
  },
  {
    id: 23,
    name: "Simran",
    role: "Systems Analyst",
    bio: "Analyzes and improves system performance.",
    gender: "Female",
  },
  {
    id: 24,
    name: "Raj",
    role: "Embedded Systems Engineer",
    bio: "Works on hardware-software integration.",
    gender: "Male",
  },
  {
    id: 25,
    name: "Priya",
    role: "Tech Support Engineer",
    bio: "Provides technical assistance to clients.",
    gender: "Female",
  },
  {
    id: 26,
    name: "Harsh",
    role: "Web Developer",
    bio: "Crafts user-friendly websites and apps.",
    gender: "Male",
  },
  {
    id: 27,
    name: "Lina",
    role: "IT Project Manager",
    bio: "Oversees tech projects from start to finish.",
    gender: "Female",
  },
  {
    id: 28,
    name: "Amit",
    role: "Robotics Engineer",
    bio: "Develops intelligent robots for automation.",
    gender: "Male",
  },
  {
    id: 29,
    name: "Pooja",
    role: "QA Engineer",
    bio: "Tests applications to ensure flawless performance.",
    gender: "Female",
  },
  {
    id: 30,
    name: "Sahil",
    role: "AR/VR Developer",
    bio: "Builds immersive virtual experiences.",
    gender: "Male",
  },
];

export default empData;
